#!/usr/bin/env bash
# Build the isomorphic app: one wasm client + one native server binary that
# serves it. Needs: machin (v0.107+), zig (the C->wasm compiler), and
# machin-web-ui (the Tailwind engine; set MACHIN_WEB_UI=/path/to/binary).
set -euo pipefail
cd "$(dirname "$0")"
MACHIN="${MACHIN:-machin}"
MWU="${MACHIN_WEB_UI:-machin-web-ui}"

# 1. stylesheet: scan the app + components for Tailwind classes.
"$MWU" css src components --theme theme.json -o web/tw.css

# 2. embed the generic JS host + the stylesheet (JSON escaping == MFL escaping).
python3 - <<'PY' > src/assets_gen.src
import functools, json
json.dumps = functools.partial(json.dumps, ensure_ascii=False)  # MFL has no \uXXXX
print('// assets_gen.src — GENERATED by build.sh. Do not hand-edit.')
print('func host_js() (s) { s = ' + json.dumps(open('web/host.js').read()) + ' }')
print('func tw_css_text() (s) { s = ' + json.dumps(open('web/tw.css').read()) + ' }')
PY

# 3. wasm CLIENT: reactive runtime + shared view + components + client logic.
"$MACHIN" encode framework/reactive.src components/*.src src/models.src src/client.src > client.mfl
"$MACHIN" build client.mfl --target wasm -o app.wasm
echo "built ./app.wasm ($(wc -c < app.wasm) bytes)"

# 4. native SERVER: machweb + flags + shared view + components + routes.
"$MACHIN" encode framework/machweb.src framework/flags.src components/*.src src/models.src src/server.src src/assets_gen.src > server.mfl
"$MACHIN" build server.mfl -o app
echo "built ./app"
echo "run:  ./app        (then open http://localhost:48100/)"
